# Generated by Django 4.0.4 on 2022-05-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainTicket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='availability',
        ),
        migrations.AlterField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_trip', to='TrainTicket.train', verbose_name='train'),
        ),
    ]
