# Generated by Django 4.0.4 on 2022-05-18 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainTicket', '0002_remove_ticket_availability_alter_trip_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='tariff',
        ),
        migrations.AlterField(
            model_name='privilege',
            name='category',
            field=models.CharField(choices=[('SCHOOL', 'school'), ('STUDENTS', 'students'), ('CHILDREN', 'children'), ('VETERANS', 'veterans'), ('PENSIONERS', 'pensioners'), ('PERSONS WITH DISABILITIES', 'persons with disabilities')], max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(54)], verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='TrainTicket.train', verbose_name='train'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='way_arrival',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='way_arrival'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='way_departure',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='way_departure'),
        ),
        migrations.AlterField(
            model_name='user',
            name='docs',
            field=models.CharField(max_length=11, verbose_name='docs'),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='capacity',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(54)], verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='class_wagon',
            field=models.CharField(choices=[('RESERVED SEAT', 'reserved seat'), ('COUPE', 'coupe'), ('SW', 'SW')], max_length=255, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='wagon',
            name='name',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='wagon'),
        ),
    ]
